/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2023 Sky UK
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef MEDIA_SEGMENTS_H_
#define MEDIA_SEGMENTS_H_

#include <string>

namespace
{
const std::string kAudioSegments[] = {"plhyftrsf",
                                      "pp[;,6mkf]",
                                      "ogjow",
                                      "svgywwx",
                                      "svrvy63fbw1sxg",
                                      "gtw-94b",
                                      "0kine64hd~;envss",
                                      "dfc",
                                      "-wqg0",
                                      "nxwfy5fvbgg^sfh7&",
                                      "fhji94gjbf",
                                      "gq9ugrqhjbfds",
                                      "svrvy63fbw1sxg",
                                      "dfc",
                                      "fhji94gjbf",
                                      "dfc",
                                      "xnute",
                                      "rj=wokgkb3333",
                                      "fhji94gjbf",
                                      "ge943pv",
                                      "dfc",
                                      "g0494vf",
                                      "bijtw0grkf",
                                      "49fait5",
                                      "fso4[;dw]",
                                      "gjkt92ijs",
                                      "gre94",
                                      "pp[;,6mkf]",
                                      "ge-q[[]]",
                                      "ge943pv",
                                      "o",
                                      "44444444",
                                      "plhyftrsf",
                                      "gre94",
                                      "xnute",
                                      "f65eggd",
                                      "g04[]",
                                      "fso4[;dw]",
                                      "803batvgff",
                                      "ogjow",
                                      "gjkt92ijs",
                                      "fgrejvfd",
                                      "fgrejvfd",
                                      "plhyftrsf",
                                      "5",
                                      "gjkt92ijs",
                                      "9jsonf",
                                      "0g",
                                      "xnute",
                                      "0g",
                                      "g04[]",
                                      "0g",
                                      "gre94",
                                      "svrvy63fbw1sxg",
                                      "9jsonf",
                                      "nxwfy5fvbgg^sfh7&",
                                      "gebjyr3ssggf",
                                      "g0e9r0[fsss]",
                                      "0kine64hd~;envss",
                                      "66h",
                                      "44444444",
                                      "9jsonf",
                                      "svrvy63fbw1sxg",
                                      "gf0iksikgs",
                                      "ge-q[[]]",
                                      "9jsonf",
                                      "ge943pv",
                                      "gre94",
                                      "nxwfy5fvbgg^sfh7&",
                                      "ge-q[[]]",
                                      "svgywwx",
                                      "44444444",
                                      "803batvgff",
                                      "0kine64hd~;envss",
                                      "i9invnd",
                                      "vfe83",
                                      "ge-q[[]]",
                                      "svgywwx",
                                      "94FG",
                                      "vfe83",
                                      "ge943pv"};

const std::string kVideoSegments[] = {"lloefewhrwohruwhfr9eee8833hbcjka",
                                      "hyrejhye y6u2255y6858geqszz",
                                      "nvid9",
                                      "#mcuruiw83udbhc",
                                      "yr6w4hgsbhjk674kuur",
                                      "hrjkl8p09[jtrwhstry5twyyuhhgdhtyww455y]",
                                      "cnvbvfbuhrew8383hbvbckzoaopalwlelhvrwvc",
                                      "yu764thgkio9p9trw545jjhf",
                                      "R080E",
                                      "nvid9",
                                      "yyt",
                                      "greabfdbnmur7y64wnguyoyrar55shshjw",
                                      "viru80202-idendhjx cefebfihgrwwwwcdcwd",
                                      "shtrnkkil ik;oiy,etq 525425",
                                      "nvid9",
                                      "ncie83uuwonvbbvaoaodoekjvbv  vyreifur779y",
                                      "yu764thgkio9p9trw545jjhf",
                                      "greabfdbnmur7y64wnguyoyrar55shshjw",
                                      "yr6w4hgsbhjk674kuur",
                                      "viru80202-idendhjx cefebfihgrwwwwcdcwd",
                                      "ncie83uuwonvbbvaoaodoekjvbv  vyreifur779y",
                                      "g5u7khdhg;popuyteyeyjhdjy",
                                      "cnvbvfbuhrew8383hbvbckzoaopalwlelhvrwvc",
                                      "g5u7khdhg;popuyteyeyjhdjy",
                                      "fhttwtjbts5568khdtjy",
                                      "hyrejhye y6u2255y6858geqszz",
                                      "ku00-uyuj766677jkutjytydyj",
                                      "hrjkl8p09[jtrwhstry5twyyuhhgdhtyww455y]",
                                      "viru80202-idendhjx cefebfihgrwwwwcdcwd",
                                      "ku00-uyuj766677jkutjytydyj",
                                      "htrkuyr",
                                      "cnvbvfbuhrew8383hbvbckzoaopalwlelhvrwvc",
                                      "jkl;p'#tshr4faggra",
                                      "yu764thgkio9p9trw545jjhf",
                                      "shtrnkkil ik;oiy,etq 525425",
                                      "htrkuyr",
                                      "ju;p'#hsgr55hthghh",
                                      "fhttwtjbts5568khdtjy",
                                      "jkl;p'#tshr4faggra",
                                      "hrtjnaty54",
                                      "yr6w4hgsbhjk674kuur",
                                      "shtrnkkil ik;oiy,etq 525425",
                                      "huykil0[-thtshngds5435yjjiulkitgdhhh]",
                                      "#mcuruiw83udbhc",
                                      "G9042HG",
                                      "hdml;pup'654sfshgshyu65tgni5566754ui76i",
                                      "shtrnkkil ik;oiy,etq 525425",
                                      "yyt",
                                      "fdshyj7647whyjdjl;;pyuhdgtyhyjey",
                                      "htrkuyr",
                                      "G9042HG",
                                      "trjjyte",
                                      "cnvbvfbuhrew8383hbvbckzoaopalwlelhvrwvc",
                                      "yyt",
                                      "hdth4y67ggshqqq125tjytel7t",
                                      "fhttwtjbts5568khdtjy",
                                      "ngkyirlkrst45ghmn,",
                                      "ku00-uyuj766677jkutjytydyj",
                                      "hyrejhye y6u2255y6858geqszz",
                                      "shtrnkkil ik;oiy,etq 525425",
                                      "yyt",
                                      "#mcuruiw83udbhc",
                                      "yr6w4hgsbhjk674kuur",
                                      "shtrnkkil ik;oiy,etq 525425",
                                      "g5u7khdhg;popuyteyeyjhdjy"
                                      "fhttwtjbts5568khdtjy",
                                      "yu764thgkio9p9trw545jjhf",
                                      "hyrejhye y6u2255y6858geqszz",
                                      "viru80202-idendhjx cefebfihgrwwwwcdcwd",
                                      "htrkuyr",
                                      "ngkyirlkrst45ghmn,",
                                      "nvid9",
                                      "g5u7khdhg;popuyteyeyjhdjy",
                                      "jkl;p'#tshr4faggra",
                                      "#mcuruiw83udbhc",
                                      "hrjkl8p09[jtrwhstry5twyyuhhgdhtyww455y]",
                                      "greabfdbnmur7y64wnguyoyrar55shshjw",
                                      "ncie83uuwonvbbvaoaodoekjvbv  vyreifur779y",
                                      "ngkyirlkrst45ghmn,",
                                      "G9042HG",
                                      "ncie83uuwonvbbvaoaodoekjvbv  vyreifur779y",
                                      "hrjkl8p09[jtrwhstry5twyyuhhgdhtyww455y]"};
} // namespace

#endif // MEDIA_SEGMENTS_H_
