if(NOT NATIVE_BUILD)

    find_path(RDKPERF_INCLUDE_DIR NAMES rdk_perf.h)
    find_library(RDKPERF_LIBRARY NAMES rdkperf)

    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(RDKPERF DEFAULT_MSG RDKPERF_LIBRARY RDKPERF_INCLUDE_DIR)

    if(RDKPERF_FOUND)
      set(RDKPERF_LIBRARIES ${RDKPERF_LIBRARY})
      set(RDKPERF_INCLUDE_DIRS ${RDKPERF_INCLUDE_DIR})
      message(STATUS "Found rdkperf: ${RDKPERF_INCLUDE_DIR} ${RDKPERF_LIBRARY}")
    else()
      set(RDKPERF_LIBRARIES "")
      set(RDKPERF_INCLUDE_DIRS "")
      message(STATUS "Could NOT find rdkperf")
    endif()
else()
    set(RDKPERF_INCLUDE_DIRS "")
    set(RDKPERF_LIBRARIES "")
endif()