name: Protobuf breaking change detection

on:
  pull_request:
    branches: [ "Protobuf_experiments", "rdkcentral:Protobuf_experiments" ]
  push:
    branches: [ "Protobuf_experiments", "rdkcentral:Protobuf_experiments" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: bufbuild/buf-setup-action@v1.25.0

      #- name: Lint
      #  uses: bufbuild/buf-lint-action@v1
      #  with:
      #    input: proto

      - name: Breaking change detection against `master`
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: https://github.com/rdkcentral/rialto.git#branch=master,ref=HEAD~1,subdir=proto

      - name: Push breaking change comments
       - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
